# https://docs.github.com/en/actions/reference/metadata-syntax-reference
name: "deepl-action"
description: "Translate a text file using DeepL API"
inputs:
  deepl-auth-key:
    description: "Your DeepL API key"
  github-token:
    description: "GitHub token for creating pull requests"
  source-file:
    description: "Path to the source text file to be translated"
  source-lang:
    description: "Language code of the source text"
  target-file:
    description: "Path to the target text file where the translation will be saved"
  target-lang:
    description: "Language code of the target text"
runs:
  using: "node20"
  main: "dist/main.js"
